# Generated by Django 4.0.5 on 2022-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='likepost',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
