# Generated by Django 4.0.5 on 2022-06-06 11:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_followerscount_alter_likepost_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=cloudinary.models.CloudinaryField(default='user.png', max_length=255, verbose_name='image'),
        ),
    ]
