# Generated by Django 4.0.5 on 2022-06-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('post_id', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
