# Generated by Django 4.0.5 on 2022-06-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_commentpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
